export const ERROR_CODE = {
	COLOR_MAX_COUNT: "COLOR_MAX_COUNT",
	COLOR_MIN_COUNT: "COLOR_MIN_COUNT",
	ALLOCATION_LIMIT_EXCEEDED: "ALLOCATION_LIMIT_EXCEEDED",
	LAST_INCOME_VALIDATION_ERROR: "LAST_INCOME_VALIDATION_ERROR",
	COLOR_USED: "COLOR_USED",
};
